package com.example.assignment4.helper;

public interface Constants {
    int OFF_SCREEN_PAGE_LIMIT = 1;
    int FRAGMENT_ONE = 0;
    int FRAGMENT_TWO = 1;
    String KEY = "value";
    String ADD="Add";
    String EDIT="Edit";
    String FUNCTION = "function";
    String VIEW ="View" ;
    String STUDENT_NAME="name";
    String STUDENT_CLASS="class";
    String STUDENT_ROLLNO ="roll";
    String DELETE ="Delete";


    public int STUDENT_LIST_EMPTY = 0;
    public int STUDENT_LIST_FILLED = 1;
    public int DB_FIRST_COLUMN = 0;
    public int DB_SECOND_COLUMN = 1;
    public int DB_THIRD_COLUMN = 2;
    public int ASYNC_PARAM1 = 1;
    public int ASYNC_PARAM2 = 2;
    public int ASYNC_PARAM3 = 3;
    public int DATABASE_VERSION = 2;
    public int MIN_ITEMS_DELETED = 0;
    public int DB_RESULT_FAIL = -1;
    public String KEY_NAME="name";
    public String KEY_ROLL="roll";
    public String KEY_CLASS="class";
    public String BUTTON_VALUE_ADD = "Add";
    public String BUTTON_VALUE_UPDATE = "Update";
    public String DB_ASYNCTASK_ADD_SUCCESS = "Added (AsyncTask)";
    public String DB_ASYNCTASK_ADD_FAIL = "Failed (AsyncTask)";
    public String DB_ASYNCTASK_DELETE_SUCCESS = "Deleted  (AsyncTask)";
    public String DB_ASYNCTASK_DELETE_FAIL = "Failed to Delete (AsyncTask)";
    public String DB_ASYNCTASK_EDIT_SUCCESS = "Edited (AsyncTask)";
    public String DB_ASYNCTASK_EDIT_FAIL = "Failed (AsyncTask)";
    public String DB_SERVICE_ADD_SUCCESS = "Added (Service)";
    public String DB_SERVICE_ADD_FAIL = "Failed (Service)";
    public String DB_SERVICE_DELETE_SUCCESS = "Deleted (Service)";
    public String DB_SERVICE_DELETE_FAIL = "Delete (Service)";
    public String DB_SERVICE_EDIT_SUCCESS = "Edited (Service)";
    public String DB_SERVICE_EDIT_FAIL = "Failed (Service)";
    public String DB_INTENTSERVICE_ADD_SUCCESS = " Added (Intent Service)";
    public String DB_INTENTSERVICE_ADD_FAIL = "Failed (Intent Service)";
    public String DB_INTENTSERVICE_DELETE_SUCCESS = "Deleted (Intent Service)";
    public String DB_INTENTSERVICE_DELETE_FAIL = "Failed (Intent Service)";
    public String DB_INTENTSERVICE_EDIT_SUCCESS = "Edited (Intent Service)";
    public String DB_INTENTSERVICE_EDIT_FAIL = "Edited (Intent Service)";
    public String BUTTON_ACTION_ASYNCTASK = "Async Task";
    public String BUTTON_ACTION_SERVICE = "Service";
    public String BUTTON_ACTION_INTENTSERVICE = "Intent Service";
    public String BUTTON_ACTION_KEY= "key";
    public String BROADCAST_SERVICE_VALUE = "service";
    public String RECEIVER_SERVICE_VALUE = "service result";
    public String BROADCAST_INTENTSERVICE_VALUE = "intent service";
    public String RECEIVER_INTENTSERVICE_VALUE = "intent service result";
    public String DATABASE_NAME = "StudentRecord.db";
    public String DB_TABLE_NAME = "Students";
    public String DB_TABLE_COL1 = "NAME";
    public String DB_TABLE_COL2 = "ROLL";
    public String DB_TABLE_COL3 = "CLASS";
    public String INTENT_SERVICE_NAME = "IntentServiceHelper";
}
